import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

interface BudgetsPageProps {
  data: any;
}

const BudgetsPage: NextPage<BudgetsPageProps> = ({ data }) => {
  console.log("🚀 ~ file: index.tsx ~ line 7 ~ data", data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http://localhost:3000/api/budgets`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}

export default BudgetsPage;
