import type { NextPage } from "next";
import Head from "next/head";
import { Expense } from "../types";

interface BudgetsPageProps {
  expenses: Expense[];
}

const BudgetsPage: NextPage<BudgetsPageProps> = ({ expenses }) => {
  console.log("🚀 ~ file: index.tsx ~ line 7 ~ expenses", expenses);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const response = await (
    await fetch(`http://localhost:3000/api/expenses`)
  ).json();

  // Pass data to the page via props
  return {
    props: {
      expenses: response.expenses,
    },
  };
}

export default BudgetsPage;
